# Generated by Django 3.1.7 on 2021-04-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='condition',
            field=models.CharField(default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
