# Generated by Django 3.1.7 on 2021-04-06 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0002_auto_20210406_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='registration',
        ),
    ]
