# Generated by Django 3.1.7 on 2021-04-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0003_remove_car_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='hijaked',
            field=models.BooleanField(default=True),
        ),
    ]
