# Generated by Django 3.1.7 on 2021-04-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapi', '0004_car_hijaked'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='registration',
            field=models.CharField(default='2000/01/01', max_length=30),
        ),
    ]
